language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
  - python manage.py migrate
# command to run tests
script:
  - python manage.py test