# Generated by Django 3.0.7 on 2020-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_urlmapping_generated_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='original_url',
            field=models.URLField(max_length=1000),
        ),
    ]
