# Generated by Django 3.0.7 on 2020-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200614_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='generated_hash',
            field=models.TextField(db_index=True, default=123, unique=True),
            preserve_default=False,
        ),
    ]
