# Generated by Django 3.0.7 on 2020-09-02 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_urlmapping_generated_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='generated_hash',
            field=models.TextField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(message='Hash should be a combination of letters and numbers.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='original_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
